In [2]:
import numpy as np
arr = np.array([23, 45, 67, 89, 10])
print(arr)

[23 45 67 89 10]


In [3]:
arr

array([23, 45, 67, 89, 10])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr[2] = 12

In [6]:
arr

array([23, 45, 12, 89, 10])

In [7]:
arr[4] = 12

In [8]:
arr


array([23, 45, 12, 89, 12])

In [ ]:
arr1 = np.array([12, 34.98, 55, True, "Pune"])


In [ ]:
import time
time.time()

In [ ]:
s = 100000

list1 = list(range(s))

arr1 = np.array(list1)

In [ ]:
#for list
start_time = time.time()
x = [i * 2 for i in list1]
time_list = time.time() - start_time
print("Time taken by list :",time_list)

In [ ]:
#for array
start_time = time.time()
y = arr1 * 2
time_arr = time.time() - start_time
print("Time taken by list :",time_arr)

In [ ]:
arr.shape

In [ ]:
arr.flatten().ndim

In [ ]:
arr.shape

In [ ]:
arr.reshape(2, 6)

In [ ]:
arr.reshape(2, -1)

In [ ]:
arr1 = np.arange(3, 13)
arr1

In [ ]:
arr1[3:7]

In [ ]:
arr[1:3, 0:2]

In [ ]:
b = np.array([[3,3], [10, 1]])


In [ ]:
a

In [ ]:
b

In [ ]:
dot_product = np.dot(a, b)
print(dot_product)

In [ ]:
#vector

vec = np.array([3, 6])

In [ ]:
np.linalg.norm(vec)

In [ ]:
#create a Numpy array of shape (3,3) with the values ranging from 1 to 9
arr = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
print(arr)

In [ ]:
#GIven is a 1D Numpy array [10,20,30,40,50], wirte a code to reverse this array

arr1 = np.array([10, 20, 30, 40, 50])
arr1[ :: -1]

In [ ]:
#craete a 5x5 Numpy array filled with zeroes and set the value of the middle element to 1

arr1 = np.array([[0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0],])

arr1[2,2] = 1
print(arr1)

In [ ]:
#Generate a Numpy array with random 20 integers between 1 and 100, replace all even numbers with -1

arr = np.random.randint(1, 101, size=20)

arr[arr % 2 == 0] = -1

print(arr)


In [ ]:
#Given a Numpy arrray a=np.array([[1, 2], [3, 4], [5,6]], extract the second column

a=np.array([[1, 2], [3, 4], [5,6]])
a[1 : : 1]